### ISSUE TITLE
Splatoon? 

### ISSUE THREAD

**Issue by Theletha** [NightmareXIV/AbyssosToolbox#1]
You mention you need splatoon, but where do you find it? 
trying to search for it only gives hits on the nintendo game..

Could you give a hint for where to get it?

**Comment by Rosabeth** [comment]
https://raw.githubusercontent.com/Eternita-S/MyDalamudPlugins/main/pluginmaster.json
put that in your dalamud setting

**Comment by Limiana** [comment]
@Theletha just find it in a plugin list and install
it's in the same repo as this plugin

**Comment by Theletha** [comment]
much obliged!
