### ISSUE TITLE
Test Splatoon Connection Doing Nothing

### ISSUE THREAD

**Issue by Tavivinyl** [NightmareXIV/AbyssosToolbox#2]
I have splatoon v2.1.1.0 and this plugin both installed, however when I hit the test splatoon connection button nothing happens. It also doesn't seem to work in the actual fight either. Any tips?

**Comment by Tavivinyl** [comment]
I have attempted uninstalling and reinstalling the toolbox.

**Comment by Limiana** [comment]
Hello.
Please upload your dalamud.log, which is located at: `%appdata%\XIVLauncher\dalamud.log`

**Comment by Dee-vo** [comment]
Seems to also just be doing nothing for me, I have the correct Splatoon version and have tried reinstalling multiple times. Hopefully this helps. 

[dalamud.log](https://github.com/NightmareXIV/AbyssosToolbox/files/9543494/dalamud.log)

**Comment by Limiana** [comment]
@DustinDBKR you have extra repo that also contains Splatoon.  This causes issues.
You should disable Splatoon, then find all instances of it and delete all of them (press trashcan button on each instance where it available) (if you're asked to restart the game, do it). After this, install Splatoon again and make sure that you're installing version from `https://raw.githubusercontent.com/NightmareXIV/MyDalamudPlugins/main/pluginmaster.json`. This should help

**Comment by Dee-vo** [comment]
@Limiana That seems to have fixed the problem, thank you.

**Comment by Tavivinyl** [comment]
Hello! The above solution worked for me as well @Limiana. Thank you.
